### ISSUE TITLE
vscode MPE 图片导入语句格式化后失败问题

### ISSUE THREAD

**Issue by electricface** [harttle/md-padding#14]
使用 vscode MPE（Markdown Preview Enhanced） 插件的导入图片并设置大小。
`@import "image.png" {width="300px" alt="image"}`
经过 md padding 格式化之后，由于在width 和 alt 之后加了一个空格，变成了
`@import "image.png" {width = "300px" alt = "image"}`
图片的解析失败了。

还有表示文件名的 "image.png" 中如果有中文的话，也会导致文件路径改变 ，而文件找不到。

**Comment by harttle** [comment]
嗯，我感觉可以加逻辑忽略 `@import` 开头的行。
