### ISSUE TITLE
想问一下这个这个插件怎么和 vue-press 做集成

### ISSUE THREAD

**Issue by liujunjia1996** [harttle/md-padding#17]
比如我写了一篇 md，走的是 github-action 自动打包部署，怎么在打包的时候顺便把这个 md 文件也格式化一下呢

**Comment by harttle** [comment]
用命令行接口，写个脚本把文件处理一遍，再用 actions/checkout 插件push回去 https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457

**Comment by liujunjia1996** [comment]
好的 我学习一下，感谢
