### ISSUE TITLE
关于格式的几个疑问

### ISSUE THREAD

**Issue by liujunjia1996** [harttle/md-padding#18]
首先我是这么用的：  

<img width="650" alt="image" src="https://user-images.githubusercontent.com/43411944/154838406-291f340d-9d66-4531-8169-f07b397498df.png">

代码片段里方法的注释格式化的是不是有问题呀  

<img width="889" alt="image" src="https://user-images.githubusercontent.com/43411944/154838229-7471e4da-c7ff-4cce-928b-08e2dc506ddb.png">

还有，关于数组的访问为什么也加了空格呀，这个可不可以做成一个配置，比如我只在代码写 "[" ，正文一般不用这种括号，所以我不需要在我的 "[" 前面加空格，看能不能提供白名单功能  

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/43411944/154838310-1e8e1c68-a5d2-4f9a-a556-5f72841f1a3b.png">

感谢博主，周末愉快

**Comment by harttle** [comment]
第一个 `/*` 丢了属于 bug， 984956923b9fcd25314482109e793e85e9ee5d21 应该 fix 了。

第二个注释内文本会当作 markdown 处理，代码（属于不应按照自然语言处理的部分）应该加反点：

```markdown
根节点 `A[0]`，
```
