### ISSUE TITLE
对picture resize 的错误格式化

### ISSUE THREAD

**Issue by MiuKaShi** [harttle/md-padding#2]
你好，最近使用了阁下的vscode版的格式化插件，大多场合下都能顺利工作，但是当在picture后引入resize参数后，格式化将导致resize 失效，如：
原来（resize起作用）：
`![ ](test.png){width=8cm} `
格式化后 （resize不起作用）
`![ ](test.png){width = 8 cm}`

这样就无法实现对图片的resize了，请问能修复吗？
感觉可以对{}[]这类符号中的英文取消格式操作，避免类似的误操作。

**Comment by MiuKaShi** [comment]
你好，谢谢你的修复，麻烦能同步更新下vscoded的插件吗，其实我大部分时间要是依赖于vscode 版本的插件
谢谢~

**Comment by harttle** [comment]
done!
