### ISSUE TITLE
Feat: 允许添加例外：“UTC±0”不应该被插入空格

### ISSUE THREAD

**Issue by StephanoGeorge** [harttle/md-padding#21]
可以考虑通过正则表达式来跳过这些片段

**Comment by harttle** [comment]
可能需要列表，可以包括两部分，

1. builtin 的，我们很确定不能加空格的，随版本发出。
2. 运行时的，允许使用者配置的。对 vscode 插件也可以有相应的配置项。

**Comment by harttle** [comment]
更新插件版本到了 v1.2.0，加这样的配置就可以了。

```json
    "mdpadding.ignoreWords": [
        "UTC±0"
    ]
```

注意 `ignoreWords` 里的情况被当做“未知类型“来处理，它和其它内容的边界不会加空格。例如 
 `伦敦时间是UTC±0` 中的 `是` 和 `U` 中间就不会自动加空格了。
