### ISSUE TITLE
YAML块中的时间会被格式化

### ISSUE THREAD

**Issue by Anduin9527** [harttle/md-padding#22]
```
date: 2022-08-08 23:53:07

date: 2022-08-08 23: 53: 07
```

**Comment by harttle** [comment]
是指类似 Jekyll 的 front matter 部分吧！我觉得可以做个可选的（默认开启）增强：

1. 识别 md 文件是否包含 front matter
2. 如果包含，按照 YAML 处理（可能现在还没有对应的[处理器](https://github.com/harttle/md-padding/blob/4eb5213fb16a1e502c9a2652d6c7ac26328930cd/src/parser/parse-code.ts#L6)，默认应该原样输出）
