### ISSUE TITLE
有什么方法能支持识别 `<br />` 等特殊 htmlTag？

### ISSUE THREAD

**Issue by obgnail** [harttle/md-padding#30]
以下文本：
```markdown
|      |                       |
| ---- | --------------------- |
|      | 123<br />456<br />789 |
```
渲染如下：
|      |                       |
| ---- | --------------------- |
|      | 123<br />456<br />789 |

可见，虽然 `123<br />456<br />789` 处于同一行，但是用户期望的是换行输出，因此 `<br />` 之后不能添加空格。

也就是说，需要识别 htmlTag 的内容，进行特殊处理。

**Comment by harttle** [comment]
是不是可以这样，假设用户使用HTML 标签时是需要自己完全控制输出，那么这时我们就不做任何处理，给用户这个自由。
也就是说我建议任何HTML 标签前后我们都不加空格，保持原样。
