### ISSUE TITLE
在正文出现 URL 的时候，插件会错误地将 QueryString 的键值对格式化

### ISSUE THREAD

**Issue by ZM-J** [harttle/md-padding#34]
例如：

http://www.google.com?foo=bar

会被格式化为

http://www.google.com?foo = bar

**Comment by obgnail** [comment]
我认为这样是合理的，因为：
1. 在 markdown 语法中，裸 url 推荐使用尖括号 `<>` 包裹
2. md_padding 不应该验证文本是否为 url

**Comment by ZM-J** [comment]
行吧，这个 [url 的语法](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses) 之前还真没了解过，之前都是发现直接把 url 写到文本中，以后注意
