### ISSUE TITLE
能否增加当前路径下递归查找指定格式文件的功能？

### ISSUE THREAD

**Issue by ykla** [harttle/md-padding#38]
如果需要处理大量不同路径的文本，目前我用的管道命令效率太低，现在默认的管道命令我用起来不支持参数 `- i` （也可能是我不会用），我现在是这么用的：

```
find "$(pwd)" -type f -name "*.md" | xargs -I {} npx mdp -i {}
```

这样效率太低了，需要十几分钟才能处理完 2000+ 文本。

能否在程序中原生支持查找当前路径及递归目录中的指定格式的文件？

非常感谢。

**Comment by harttle** [comment]
1.7.0 增加了 `--read-files` 参数，可以读入文件列表，例如：

```bash
find -type f -name '*.md' | npx md-padding@latest --read-files -i
```

比较暴力，跑之前注意备份一下。
