### ISSUE TITLE
对 Hexo 类博客中的标签语法`{% %}`内的 `key:value`的转换不符合预期

### ISSUE THREAD

**Issue by Cactusinhand** [harttle/md-padding#42]
使用 Hexo 博客框架写 Markdown 文档时，会用到大量标签语法，
例如：
```
{% codeblock title lang:c line_number:true highlight:true %}
my code
{% endcodeblock %}
```
而里面的`lang:c` 会被格式化为`lang: c`, 而这样是不符合这里的语法的。
总结就是`{% %}`内的 `key:value` 都会被转换为`key: value`。
由于我写的文档里面有太多这样的语法了，使用 md-padding 后更改 key:value 的时间和更改中英文混用的空格问题的时间差不多了😭，又因为这类关键词太多了，写入 `ignoreWords` 也不是很方便。
有什么好的方法避免吗？

**Comment by harttle** [comment]
增加了 `ignorePatterns` 参数，使用可以参考这个例子：
https://github.com/harttle/md-padding/commit/cccecc2e482bb96d5f714f742ff022e41eee31a3#diff-120a7846ec573d63c08e8b32f282492b685e194c8190d8523cbf9a1097e1d497R132-R148

vscode 插件也同步发版了：
https://github.com/harttle/md-padding-vscode/releases/tag/v1.6.0
