### ISSUE TITLE
Padding is disabled when `ignorePatterns` matches content within blockCode.

### ISSUE THREAD

**Issue by obgnail** [harttle/md-padding#45]
开发者你好，发现一个 BUG。

对于以下文本，设置 `ignorePatterns=["<br\\s*?/>"]`，会导致匹配失效。

````
```html
<br/>
```

此行及以下的内容全部被视为blockCode的内容，导致不可padding

123测试

````

原因是 blockCode 里的内容成功匹配后，会强制将文本进行切割，导致 blockCode 前后的三反引号被分割，进而导致下面的内容全部被视为blockCode的内容。

而且，ignorePatterns 检测 blockCode 里的内容也是不合理的，应该跳过 blockCode

**Comment by harttle** [comment]
good catch! 没想到会有这个问题，需要换种实现。
