### ISSUE TITLE
在代码区似乎不会被格式化

### ISSUE THREAD

**Issue by yi-Xu-0100** [harttle/md-padding#6]
例如下方代码块中的注释部分，使用插件的格式化后，中英文之间不会被添加空格，希望能够修复~

```javascript
{
    var a = 1;
}

console.log(a); //这里的a，指的是区块里的a
```

**Comment by harttle** [comment]
fixed in d9d74f9ee9c45cdbc20504f9a45bee9c9d68030c will be available on md-padding-vscode v1.1.0
